from document import load_document_main as main
import sys

"""
A simple program for loading JSON dicts into a MongoDB collection
"""

#TODO: Add support for GZIP json



if __name__ == "__main__":
    if len(sys.argv) == 3:
        main(sys.argv[1], sys.argv[2])
    elif len(sys.argv) == 4:
        main(sys.argv[1], sys.argv[2], sys.argv[3])
    else:
        print("""Usage: python load_documents_from_doc_db.py batch_files.json runtime.json [collection_name]
  where batch_files.json is a json file generated by "build_document_mapping_from_db.py"
        """)


